spring.application.name=bnb-rest

server.port=5041
logging.file.path=/opt/expressway-bnb/logs

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.compression.enabled=true
server.compression.mime-types=text/html,application/json

spring.config.import=file:/opt/expressway-bnb/conf/mysql.properties,\
    file:/opt/expressway-bnb/conf/mongodb.properties,\
    file:/opt/expressway-bnb/conf/email.properties,\
    file:/opt/expressway-bnb/conf/rabbitmq.properties,\
    file:/opt/expressway-bnb/conf/sms.properties,\
    file:/opt/expressway-bnb/conf/jwt.properties,\
    file:/opt/expressway-bnb/conf/entity-log.properties

